#!/bin/bash

resize
# let's be minimal
mount -t proc proc proc/
mount -t sysfs sys sys/
mount -o bind /dev dev/
mount -o rw,remount /

# show the blue screen of death (yes on LINUX!)
sleep 1s
fbi -noverbose -d /dev/fb0 -T 1 /etc/bsod.jpg -a
sleep 10s

# save the vmcore dmesg
vmcore-dmesg /proc/vmcore > /var/log/dmesg-crash.log
sleep 20s

# reboot
echo b > /proc/sysrq-trigger
# do not generate another panic by try to kill init
sleep 1h
