#!/bin/bash

# let's be lazy and use the openrc to init the basic sysfs and modules
openrc sysinit

# show the blue screen of death (yes on LINUX!)
sleep 1s
fbi -noverbose -d /dev/fb0 -T 1 /etc/bsod.jpg
sleep 10s

# save the vmcore dmesg
vmcore-dmesg /proc/vmcore > /var/log/dmesg-crash.log
sleep 30s

# reboot
echo b > /proc/sysrq-trigger
# do not generate another panic by try to kill init
sleep 1h
