#!/bin/bash

# use message utils
. ./utils/fancyTerminalUtils.sh --source-only
. ./utils/welcome.sh --source-only

# Seadog version
export SEADOG_MAJOR_VERSION=0
export SEADOG_MINOR_VERSION=0
export SEADOG_BUILD_VERSION=$(wget "http://microhobby.com.br/safira2/kernelbuild.php"  -q -O -)
#export SEADOG_BUILD_VERSION=$((SEADOG_BUILD_VERSION+1))
export SEADOG_BUILD_VERSION=27
export SEADOG_NAME="kleptomaniac-octopus"

# create the files from templates
function replaceVersions () {
    sed "s/{{v1}}/${SEADOG_MAJOR_VERSION}/" $1.template > $1
    sed -i "s/{{v2}}/${SEADOG_MINOR_VERSION}/" $1
    sed -i "s/{{v3}}/${SEADOG_BUILD_VERSION}/" $1
    sed -i "s/{{codename}}/${SEADOG_NAME}/" $1
}

# you can use to set how many threads for the build
if [[ ! -v JOBS ]]; then
	export JOBS=12
fi

export CLEAN="$2"
export UBOOT_BRANCH="$3"
export arg=""

# set seadog default u-boot branch
if [ "$UBOOT_BRANCH" == "" ]; then
	export UBOOT_BRANCH="v2021.04"
fi

# welcome
seadogWelcomeColor

# debug arguments
echo -e "🍟 BOARD        \t::\t $1"
echo -e "🧹 CLEAN        \t::\t ${CLEAN}"
echo -e "👢 UBOOT_BRANCH \t::\t ${UBOOT_BRANCH}"
echo -e "💪 JOBS         \t::\t ${JOBS}"
echo ""
sleep 2s

# check the arguments
case "$1" in
    "bcm2837-rpi-3b")
        # Raspberry Pi 3B+
        writeln "Seadog for Raspberry Pi 3B"

        # replace for the new version
        #replaceVersions kernel/rpi/configs/bcm2837_rpi_3b_defconfig
        replaceVersions uboot/rpi/configs/bcm2837_rpi_3b_defconfig
        #replaceVersions rootfs/common/os-release

        # compile u-boot
        ./uboot/rpi/build-raspi-3b.sh
    ;;
	"bcm2837-rpi-3bp")
		# Raspberry Pi 3B+
        writeln "Seadog for Raspberry Pi 3B+"

        # replace for the new version
        replaceVersions kernel/rpi/configs/bcm2837_rpi_3bp_defconfig
        replaceVersions uboot/rpi/configs/bcm2837_rpi_3bp_defconfig
        replaceVersions rootfs/common/os-release

        # compile u-boot
        ./uboot/rpi/build-raspi-3bp.sh

        # compile mainline Kernel
        ./kernel/rpi/build-raspi-3bp.sh

        # compile initrd
        ./initrd/do-initrd-common.sh

        # do rootfs and pack img
        ./rootfs/rpi/do-rootfs-rpi-3bp.sh
		;;
    "bcm2711-rpi-4b")
        # Raspberry Pi 4B
        writeln "Seadog for Raspberry Pi 4B"

        # replace for the new version
        replaceVersions kernel/rpi/configs/bcm2711_rpi_4b_defconfig
        replaceVersions uboot/rpi/configs/bcm2711_rpi_4b_defconfig
        replaceVersions rootfs/common/os-release

        # compile u-boot
        ./uboot/rpi/build-raspi-4b.sh

        # compile mainline Kernel
        ./kernel/rpi/build-raspi-4b.sh

        # compile initrd
        ./initrd/do-initrd-common.sh

        # do rootfs and pack img
        ./rootfs/rpi/do-rootfs-rpi-4b.sh
        ;;
	*)
		writelnError "What? 🤷"
		writelnError "🚫 ${BOLD}$1${RED} Not implemented ..."

        echo ""
        echo "Supported hardwares:"
        echo -e "Raspberry Pi 3B \t::\t bcm2837-rpi-3b"
        echo -e "Raspberry Pi 3B+ \t::\t bcm2837-rpi-3bp"
        echo -e "Raspberry Pi 4B \t::\t bcm2711-rpi-4b"

		exit 1
		;;
esac

writeln "🐶  SEADOG LINUX DISTRO v$SEADOG_MAJOR_VERSION.$SEADOG_MINOR_VERSION.$SEADOG_BUILD_VERSION"
