#!/bin/bash

# use message utils
. ./utils/fancyTerminalUtils.sh --source-only
. ./utils/welcome.sh --source-only

# you can use to set how many threads for the build
# export JOBS=12

export CLEAN="$2"
export arg=""

# welcome
seadogWelcomeColor

# check the arguments
case "$1" in
	"bcm2837-rpi-3bp")
		# Raspberry Pi 3B+
        writeln "Seadog for Raspberry Pi 3B+"

        # compile u-boot
        ./uboot/rpi/build-raspi-3bp.sh

        # compile mainline Kernel
        ./kernel/rpi/build-raspi-3bp.sh

        # do rootfs and pack img
        ./rootfs/rpi/do-rootfs-rpi-3bp.sh
		;;
	*)
		writelnError "What? 🤷"
		writelnError "🚫 ${BOLD}$1${RED} Not implemented ..."

        echo "Supported hardwares:"
        echo -e "Raspberry Pi 3B+ \t::\t bcm2837-rpi-3bp"

		exit 1
		;;
esac

countCompiles=$(wget "http://microhobby.com.br/safira2/kernelbuild.php"  -q -O -)
writeln "🐶  SEADOG LINUX DISTRO v0.1.$countCompiles"
