#!/bin/bash

function seadogBlackWelcome () {
    echo "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMNX0kdolcccccccclodk0XWMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"
    echo "MMMMMMMMMMMMMMMMMMMMMMMWNKkoc:;:ccodxxkkkxxdolc:;;:cdOKNMMMMMMMMMMMMMMMMMMMMMMMM"
    echo "MMMMMMMMMMMMMMMMMMWN0koc;;:ldOKNWMMMMXkxxONMMMMWNKkoc:;:cdkKNWMMMMMMMMMMMMMMMMMM"
    echo "MMMMMMMMMMMMMWN0xl:;;:lxOXWMMMMMMMMMXc....oWMMMMMMMMMNKOdc:;;cokKNMMMMMMMMMMMMMM"
    echo "MMMMMMMMMMMWOl;;:lx0XWMMMMMMMMMMMMMMNd...,kWMMMMMMMMMMMMMMWXOdl:;;oKWMMMMMMMMMMM"
    echo "MMMMMMMMMMWx';kXWMMMMMMMMMMMMMMMMMMMNk,..:ONMMMMMMMMMMMMMMMMMMMWXd',OWMMMMMMMMMM"
    echo "MMMMMMMMMMK;'OMMMMMMMMMMMMMMMMMMMMMMKo. .'dNMMMMMMMMMMMMMMMMMMMMMWx.cNMMMMMMMMMM"
    echo "MMMMMMMMMMX:.kWMMMMMMMMMMMMMMMMMNkd0WNl.'xWWOdOWMMMMMMMMMMMMMMMMMWo.oWMMMMMMMMMM"
    echo "MMMMMMMMMMWk';KMMMMMMMMMMMMMMMMMNd.;KNl.'xWO''kWMMMMMMMMMMMMMMMMMO';KMMMMMMMMMMM"
    echo "MMMMMMMMMMMNo.lNMMMMMMMMMMMMMMMMMNo':o,..:o,'xWMMMMMMMMMMMMMMMMMX:.kWMMMMMMMMMMM"
    echo "MMMMMMMMMMMMK;'kWMMMMMMMMMMMMMMMMMWOo:. ..cdKWMMMMMMMMMMMMMMMMMWo.lNMMMMMMMMMMMM"
    echo "MMMMMMMMMMMMWk',OXXXXXXXXXXXXXXXXXXXXKxodkKXXXXXXXXXXXXXXXNMMWXx';KMMMMMMMMMMMMM"
    echo "MMMMMMMMMMMMMNl.'::::::::::::::::::::::::::::::::::::::::ckWMKl..dWMMMMMMMMMMMMM"
    echo "MMMMMMMMMMMMMWo.lXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXWMMWK;.kMMMMMMMMMMMMMM"
    echo "MMMMMMMMMMMMMNl 'ccccccccccccccccccccccccccccccccccccccccccccc:..xWMMMMMMMMMMMMM"
    echo "MMMMMMMMMMMMMO'                                                  ;KMMMMMMMMMMMMM"
    echo "MMMMMMMMMMMMMO.                                                  ;KMMMMMMMMMMMMM"
    echo "MMMMMMMMMMMMMNx'                                                ,OWMMMMMMMMMMMMM"
    echo "MMMMMMMMMMMMMMWK:                                             .dXMMMMMMMMMMMMMMM"
    echo "MMMMMMMMMMMMMMM0,  ..                                     .'  .xWMMMMMMMMMMMMMMM"
    echo "MMMMMMMMMMMMMMNc  ,Od. .;c,..                     ..';;.  :0c  ,KMMMMMMMMMMMMMMM"
    echo "MMMMMMMMMMMMMM0'  oNx. .OMWKd,';llcc:::;;:::cll:.'cONWK;  cNk. .xMMMMMMMMMMMMMMM"
    echo "MMMMMMMMMMMMMMk. .kMk. .xWMNc  cXMMMMMWWWWMMMMWd. ,0MMO' .dWK,  lNMMMMMMMMMMMMMM"
    echo "MMMMMMMMMMMMMWo  '0MX;  :XMWKkkKWMMMMMMMMMMMMMMXkk0NMWo. .OMX:  :XMMMMMMMMMMMMMM"
    echo "MMMMMMMMMMMMMNc  ;XMWx. .xWMMMMMMMMMMMMMMMMMMMMMMMMMM0,  lNMWo  '0MMMMMMMMMMMMMM"
    echo "MMMMMMMMMMMMMK,  lNMMXc  '0MMMMMMMMMMMMMMMMMMMMMMMMMXc  ,0MMMk. .kMMMMMMMMMMMMMM"
    echo "MMMMMMMMMMMMMk. .xWMMMK;  ;KMMMMMMMMMMMMMMMMMMMMMMMNl  .kWMMM0'  oWMMMMMMMMMMMMM"
    echo "MMMMMMMMMMMMWo  '0MMMMMO'  cXMMMMMNkoccccclxKWMMMMWd. .dWMMMMNc  ;XMMMMMMMMMMMMM"
    echo "MMMMMMMMMMMM0,  lNMMMMMWx. .oNMMWO;   ...   .xNMMWk.  lNMMMMMWx. .xWMMMMMMMMMMMM"
    echo "MMMMMMMMMMMNl  'OMMMMMMMNo. .kWMX;  ,k000Oc  .OMM0,  :XMMMMMMMX:  ;KMMMMMMMMMMMM"
    echo "MMMMMMMMMMWk. .oWMMMMMMMMK,  cNMX:  'xKXKO:  'OMWx. .kMMMMMMMMMO. .oWMMMMMMMMMMM"
    echo "MMMMMMMMMMX:  ;KMMMMMMMMMNc  :XMW0:.  ...   ,kWMWo  '0MMMMMMMMMNl  '0MMMMMMMMMMM"
    echo "MMMMMMMMMMO' .dWMMMMMMMMMWx. .oXWMNO:     ,xNMMNk'  cNMMMMMMMMMMO. .dWMMMMMMMMMM"
    echo "MMMMMMMMMMk. .xMMMMMMMMMMMNd.  ':ll:.     .;llc,. .cKMMMMMMMMMMM0'  oWMMMMMMMMMM"
    echo "MMMMMMMMMM0'  oWMMMMMMMMMMMWd.     ..;odo:..      cXMMMMMMMMMMMWk. .dWMMMMMMMMMM"
    echo "MMMMMMMMMMNl  .xNMMMMMMMMMW0;  'xOO0XWMMMWX0OOk:  .kWMMMMMMMMMWO,  ;KMMMMMMMMMMM"
    echo "MMMMMMMMMMMXl. .:kXWMMMWN0l.  ,OWMMMMMMMMMMMMMMKc. .ckXWMMMWNOl.  ;0MMMMMMMMMMMM"
    echo "MMMMMMMMMMMMWk;.  .,:cc;'.  'oXMMMMMMMMMMMMMMMMMNx,.  .;:c:;'   ,dXMMMMMMMMMMMMM"
    echo "MMMMMMMMMMMMMMN0o:'......;lkXWMMMMMMMMMMMMMMMMMMMMNOo:'......;lkXWMMMMMMMMMMMMMM"
    echo "MMMMMMMMMMMMMMMMMWX0OkkOKNMMMMMMMMMMMMMMMMMMMMMMMMMMMWX0kkk0XNMMMMMMMMMMMMMMMMMM"

    sleep 10s
}

function seadogWelcome () {
    echo "                                 ''.-:////:-.''                                 "
    echo "                           '-/syhdysso+//+osshdhyo/.'                           "
    echo "                      '-+shhs+-.       '        .:oyhhs/-'                      "
    echo "                 ':+ydhs+-'          .hdds           .-+yhhs/-'                 "
    echo "             '/ydhs/.'               .ddmh                '-+yhdy:'             "
    echo "            /ms.                      .dy'                      -hd-            "
    echo "           .M/                       /dNNh-                       yd'           "
    echo "           .M/                   '-   'hy   '.                    ym'           "
    echo "            sm.                  .hm- 'hy  :Ns'                  :N/            "
    echo "            'my                   'Ns''hy .dd                    my             "
    echo "             :M:                   'ohdNNdh/'                   sm.             "
    echo "              sd.                     '+/                      :N/              "
    echo "              'Ndyssssssssssssssssssyssssssyssssssssssssyo'  :smh               "
    echo "               hm........................................'   '-N+               "
    echo "               hN:::::::::::::::::::::::::::::::::::::::::::::/N+               "
    echo "              :MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMm'              "
    echo "              sMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM-              "
    echo "              'dMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMs               "
    echo "               '/mMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMy-                "
    echo "                .mMMdNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmNMN/                 "
    echo "               'hMM+ dMMdhmNMMMMMMMMMMMMMMMMMMMMMMMMNmhMMM..MMN.                "
    echo "               /NMd' hMM/   -/+sssyhmmmmmmmdhysys+:.  'MMN' oMMs                "
    echo "               +MMy  sMMo   .mMm'              yMM-   -MMh' /MMd                "
    echo "               yMM:  -MMm   '/++               :++'   yMMo  .mMm.               "
    echo "               MMM.  'hMM+                           -NMN.   dMN:               "
    echo "              'MMm'   -NMm-                         'hMM+    yMM+               "
    echo "              +MMs     +MMd'                        sMMy'    :MMy               "
    echo "              yMM+      oMMy'       '-----.        +MMd      .MMM               "
    echo "             -NMN'       hMMo     .hNMMMMMNd/     :NMm-       yMM+              "
    echo "             yMMo        .dMN/   .mMNo:--/mMM/   .NMN:        :NMd.             "
    echo "            /NMd'         -MMN   -MMN.   'yMMs   yMMo          sMMs             "
    echo "           'dMM-          .MMM    +NMMhohNMMh    yMM+          .dMN:            "
    echo "           :MMd           'hMM/    .+hMMMmo-    -mMN.           oMMs            "
    echo "           +MMo            .dMMh/--:+dMMMNo:--:sNMN/            -MMy'           "
    echo "           /MMs             'oMMMMMMMMh+yNMMMMMMMd.             :MMy            "
    echo "           .mMM:            .dMMs///-'    .://+NMM-            .dMN/            "
    echo "            -mMNs.        '/mMMs               :NMNo'        '/mMNo             "
    echo "             .sNMNho/--:+ymMMd:                 .yMMNho:--:+ymMMh-              "
    echo "               .+hNMMMMMMNds-                     .+hNMMMMMMNdo-                "
    echo "                   '.-:-.'                           ''.::-''                   "

    sleep 2s
}

function seadogMiniWelcome () {
    echo "              .://+/////:.              "
    echo "         .//+/:'   //   ':////.         "
    echo "      /+/-'       'ys        ':/+:      "
    echo "     'y          ''ys''          h'     "
    echo "      s-        'y-+/:s         :o      "
    echo "      'y          :so:         'y'      "
    echo "       +s//////////////////// 'y:       "
    echo "       odyyyyyyyyyyyyyyyyyyyyyyd/       "
    echo "       sMMMMMMMMMMMMMMMMMMMMMMMM+       "
    echo "        sMNMMMMMMMMMMMMMMMMMMNM:        "
    echo "       'Ns/M++yddmNNNNmdhs+hM'my        "
    echo "       :M--M/ /h       -h' hd sN        "
    echo "       oN' hd'            -M/ /M-       "
    echo "       dh  .my    '..    .my  .M+       "
    echo "      -M/   -N+ 'hmyyN+  dd'   hd       "
    echo "      dd     sM 'mh:+Ns /M-    -N+      "
    echo "     .M:     -No..sMN/'-dd      yd      "
    echo "     .M+      /Mhys:+yymN'     'dh      "
    echo "      :my:..:sN+       'hm+-.-+dh.      "
    echo "        :osyo/'          .+sys+.        "

    sleep 10s
}

function seadogWelcomeColor () {
    cat ./rootfs/common/welcome

    sleep 2s
}
